version: "3.9"

services:
  djangonext:
    container_name: csi29-devcontainer
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    volumes:
      - .:/www
    working_dir: /www
    command: tail -f /dev/null
    ports:
      - "8000:8000"  # Django
      - "3000:3000"  # React
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: csi29-db
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
