version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - .:/app
    working_dir: /app/backend
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
